# Creating arrays

## 1D array

In [8]:
import numpy as np

a = np.array([1,2,3,4]) 
print("shape:"+str(a.shape))
print("ndim:"+str(a.ndim))

shape:(4,)
ndim:1


## 2D array

In [16]:
b = np.array([[0,1,2],[3,4,5]]) # 2x3 array
b.shape ## shape

(2, 3)

In [14]:
len(b) # size of the first dimension

2

## 3D array

In [18]:
c = np.array([[[1], [2]],[[3],[4]]])
c.shape

(2, 2, 1)

In [19]:
c.ndim ## number of dimension

3

## Functions to create arrays

In [21]:
## evenly spaced arrays

a = np.arange(12) # 0, ..., n-1
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
b = np.arange(5,17,3)
b

array([ 5,  8, 11, 14])

In [31]:
## by number of points
c = np.linspace(1, 2, 6) # start, end, number of points. The array includes the end value by default
c

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ])

In [ ]:
d = np.linspace(1, 2, 6, endpoint= False)