# Creating arrays

## 1D array

In [8]:
import numpy as np

a = np.array([1,2,3,4]) 
print("shape:"+str(a.shape))
print("ndim:"+str(a.ndim))

shape:(4,)
ndim:1


## 2D array

In [16]:
b = np.array([[0,1,2],[3,4,5]]) # 2x3 array
b.shape ## shape

(2, 3)

In [14]:
len(b) # size of the first dimension

2

## 3D array

In [18]:
c = np.array([[[1], [2]],[[3],[4]]])
c.shape

(2, 2, 1)

In [19]:
c.ndim ## number of dimension

3

## Functions to create arrays

In [21]:
## evenly spaced arrays

a = np.arange(12) # 0, ..., n-1
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
b = np.arange(5,17,3)
b

array([ 5,  8, 11, 14])

In [31]:
## by number of points
c = np.linspace(1, 2, 6) # start, end, number of points. The array includes the end value by default
c

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ])

In [33]:
d = np.linspace(1, 2, 6, endpoint=False) ## the default behaviour of linspace including endpoint can be changed
d

array([ 1.        ,  1.16666667,  1.33333333,  1.5       ,  1.66666667,
        1.83333333])

In [36]:
## common matrices
mat1 = np.ones((3,4))
mat1

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [38]:
mat0 = np.zeros((2,2))
mat0

array([[ 0.,  0.],
       [ 0.,  0.]])

In [40]:
matI = np.eye(3) ## np.eye expects an integer
matI

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [42]:
matDiag = np.diag((1,2,3,4))
matDiag

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [44]:
## random array
np.random.seed(1887)
np.random.rand(3) ## uniform between [0,1]

array([ 0.91038498,  0.73689717,  0.20794549])

In [45]:
np.random.randn(3) ## randn = Gaussian 

array([ 0.15230822,  0.60260711, -1.09874763])

In [48]:
np.random.randint(low=3, high=10, size=7) ## random integer

array([3, 6, 5, 3, 6, 5, 3])

In [52]:
## empty
np.empty((2,3), dtype=float) ## the data is arbitrary 

array([[ 1.        ,  1.16666667,  1.33333333],
       [ 1.5       ,  1.66666667,  1.83333333]])