# Array manipulations

In [1]:
import numpy as np
import matplotlib
%matplotlib inline

## Exercise 1

In [14]:
a = np.arange(1, 16).reshape(5, 3, order='F')
a

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [18]:
a2 = a[(1,3),:]
a2

array([[ 2,  7, 12],
       [ 4,  9, 14]])

## Exercise 2

In [20]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
b = np.array([1., 5, 10, 15, 20])
b

array([  1.,   5.,  10.,  15.,  20.])

In [23]:
a/b[:,np.newaxis] ## divide by column

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.2       ,  1.4       ,  1.6       ,  1.8       ],
       [ 1.        ,  1.1       ,  1.2       ,  1.3       ,  1.4       ],
       [ 1.        ,  1.06666667,  1.13333333,  1.2       ,  1.26666667],
       [ 1.        ,  1.05      ,  1.1       ,  1.15      ,  1.2       ]])

In [24]:
a/b # divide by row

array([[  0.        ,   0.2       ,   0.2       ,   0.2       ,   0.2       ],
       [  5.        ,   1.2       ,   0.7       ,   0.53333333,   0.45      ],
       [ 10.        ,   2.2       ,   1.2       ,   0.86666667,   0.7       ],
       [ 15.        ,   3.2       ,   1.7       ,   1.2       ,   0.95      ],
       [ 20.        ,   4.2       ,   2.2       ,   1.53333333,   1.2       ]])

## Exercise 3

In [26]:
a = np.random.rand(30).reshape(10,3)
a

array([[ 0.82670451,  0.84997397,  0.41444695],
       [ 0.29629091,  0.93151163,  0.20923258],
       [ 0.41019157,  0.52190185,  0.00131353],
       [ 0.22100794,  0.92791843,  0.52630287],
       [ 0.1803377 ,  0.97738092,  0.36942578],
       [ 0.36414014,  0.16320963,  0.45217938],
       [ 0.40650749,  0.08811856,  0.70742779],
       [ 0.72269461,  0.52870765,  0.6357838 ],
       [ 0.42481757,  0.83903479,  0.62906008],
       [ 0.47298915,  0.20527599,  0.47569818]])

In [40]:
nearestInd = np.argsort(abs(a - 0.5), axis=1)[:,0]
nearestInd

array([2, 0, 1, 2, 2, 2, 0, 1, 0, 2], dtype=int32)

In [41]:
a[np.arange(10), nearestInd]

array([ 0.41444695,  0.29629091,  0.52190185,  0.52630287,  0.36942578,
        0.45217938,  0.40650749,  0.52870765,  0.42481757,  0.47569818])