# Elementwise operations

## With scalars

In [1]:
import numpy as np

a = np.array([1,2,3,4])
a + 1

array([2, 3, 4, 5])

In [2]:
10**a ## expotential

array([   10,   100,  1000, 10000], dtype=int32)

In [3]:
b = np.ones(4) + 1
b

array([ 2.,  2.,  2.,  2.])

In [4]:
a - b

array([-1.,  0.,  1.,  2.])

In [5]:
a * b

array([ 2.,  4.,  6.,  8.])

In [7]:
j = np.arange(5)
3**(j+1)-j

array([  3,   8,  25,  78, 239])

A small time benchmark

In [8]:
a = np.arange(10000)
%timeit a + 1

37.5 µs ± 6.75 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
an = range(1000)
%timeit [i+1 for i in an]

505 µs ± 115 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
