# Elementwise operations

## With scalars

In [2]:
import numpy as np

a = np.array([1,2,3,4])
a + 1

array([2, 3, 4, 5])

In [3]:
10**a ## expotential

array([   10,   100,  1000, 10000])

In [4]:
b = np.ones(4) + 1
b

array([ 2.,  2.,  2.,  2.])

In [5]:
a - b

array([-1.,  0.,  1.,  2.])

In [6]:
a * b

array([ 2.,  4.,  6.,  8.])

In [7]:
j = np.arange(5)
3**(j+1)-j

array([  3,   8,  25,  78, 239])

A small time benchmark: element-wise operation with np is about 15 times faster on the tested machine.

In [8]:
a = np.arange(10000)
%timeit a + 1

7.32 µs ± 573 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
an = range(1000)
%timeit [i+1 for i in an]

72.8 µs ± 2.09 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Note array multiplication is not matrix multiplication

In [10]:
c = np.ones((3,3))
c*c ## array multip

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
c.dot(c) ## .dot does matrix multiplication

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [12]:
[2**0, 2**1, 2**2, 2**3, 2**4]

[1, 2, 4, 8, 16]

In [13]:
j = np.arange(10)
a = 2**(3*j)-j
print(a)

[        1         7        62       509      4092     32763    262138
   2097145  16777208 134217719]


## Other options

In [14]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,3])
a == b

array([False,  True, False, False], dtype=bool)

In [15]:
a >= b

array([False,  True,  True,  True], dtype=bool)

In [16]:
## Array-wise comparisons with np.array
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

np.array_equal(a,b)


False

In [17]:
np.array_equal(c, a)

True

In [19]:
# Logical and and or
a = np.array([0,0,1,1], dtype=bool)
b = np.array([0,1,0,1], dtype=bool)
np.logical_and(a,b)

array([False, False, False,  True], dtype=bool)

In [20]:
np.logical_or(a,b)

array([False,  True,  True,  True], dtype=bool)

In [21]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [23]:
np.log(a)

/Users/FamilieZhang/Software/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436])

In [27]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [31]:
a = np.triu(np.ones((3,3)),1)
a

array([[ 0.,  1.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [32]:
a.T

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  1.,  0.]])

Note that __transpose__ is a view, but a copy.

In [36]:
a = np.array((0,1,2,3+1e-6))
b = np.array((0,1,2-1e-6,3))
np.array_equal(a,b)

False

In [37]:
np.allclose(a,b)

True

## Basic reductions

In [38]:
x = np.array([3,4,5,6])
np.sum(x)

18

In [39]:
x.sum()

18

### Sum by rows and by columns

In [43]:
x = np.array([[1,3],[4,5]])
x

array([[1, 3],
       [4, 5]])

In [44]:
x.sum(axis=0) ## columns - first dimension!! Different from R

array([5, 8])

In [47]:
x[:,0].sum(), x[:,1].sum()

(5, 8)

In [48]:
x.sum(axis=1) ## rows - the second dimension!! Different from R

array([4, 9])

In [49]:
x[0,:].sum(), x[1,:].sum()

(4, 9)

In [50]:
## Example of high-dimensional arrays
xh = np.random.rand(2,2,2)
xh

array([[[ 0.81070369,  0.25226759],
        [ 0.90982591,  0.30164638]],

       [[ 0.47884932,  0.01235543],
        [ 0.19665988,  0.12871311]]])

In [52]:
xh.sum(axis=2)

array([[ 1.06297128,  1.21147229],
       [ 0.49120476,  0.32537299]])

In [53]:
xh.sum(axis=1)

array([[ 1.7205296 ,  0.55391397],
       [ 0.6755092 ,  0.14106854]])

In [54]:
xh.sum(axis=0)

array([[ 1.28955301,  0.26462302],
       [ 1.10648579,  0.43035949]])

In [56]:
xh[0,1,:].sum()

1.2114722919987069

### Max and min, and argmax and argmin

In [57]:
x = np.array([1,3,5,2])
x.min()

1

In [58]:
x.max()

5

In [59]:
x.argmin() ## which.min in R

0

In [60]:
x.argmax()

2

### Logical operations

In [62]:
np.all([True, True, False])

False

In [63]:
np.any([True, True, False])

True

In [65]:
a = np.zeros((100,100))
np.any(a != 0)

False

In [69]:
## np.all() is equal to boolarray.all()
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = b + 1
((a <= b) & (b <= c)).all()

True

In [68]:
np.all(((a <= b) & (b <= c)))

True

### Statistics

In [70]:
x = np.array([1,2,3,1])
x.mean()

1.75

In [71]:
## note that the median is not a method of array, but rather a function
np.median(x)

1.5