# Elementwise operations

## With scalars

In [3]:
import numpy as np

a = np.array([1,2,3,4])
a + 1

array([2, 3, 4, 5])

In [4]:
10**a ## expotential

array([   10,   100,  1000, 10000], dtype=int32)

In [5]:
b = np.ones(4) + 1
b

array([ 2.,  2.,  2.,  2.])

In [6]:
a - b

array([-1.,  0.,  1.,  2.])

In [7]:
a * b

array([ 2.,  4.,  6.,  8.])

In [8]:
j = np.arange(5)
3**(j+1)-j

array([  3,   8,  25,  78, 239])

A small time benchmark: element-wise operation with np is about 15 times faster on the tested machine.

In [9]:
a = np.arange(10000)
%timeit a + 1

24.1 µs ± 6.25 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
an = range(1000)
%timeit [i+1 for i in an]

159 µs ± 14.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Note array multiplication is not matrix multiplication

In [11]:
c = np.ones((3,3))
c*c ## array multip

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
c.dot(c) ## .dot does matrix multiplication

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [13]:
[2**0, 2**1, 2**2, 2**3, 2**4]

[1, 2, 4, 8, 16]

In [14]:
j = np.arange(10)
a = 2**(3*j)-j
print(a)

[        1         7        62       509      4092     32763    262138
   2097145  16777208 134217719]


## Other options

In [15]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,3])
a == b

array([False,  True, False, False], dtype=bool)

In [16]:
a >= b

array([False,  True,  True,  True], dtype=bool)

In [17]:
## Array-wise comparisons with np.array
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

np.array_equal(a,b)


False

In [18]:
np.array_equal(c, a)

True