# Elementwise operations

## With scalars

In [2]:
import numpy as np

a = np.array([1,2,3,4])
a + 1

array([2, 3, 4, 5])

In [3]:
10**a ## expotential

array([   10,   100,  1000, 10000])

In [4]:
b = np.ones(4) + 1
b

array([ 2.,  2.,  2.,  2.])

In [5]:
a - b

array([-1.,  0.,  1.,  2.])

In [6]:
a * b

array([ 2.,  4.,  6.,  8.])

In [7]:
j = np.arange(5)
3**(j+1)-j

array([  3,   8,  25,  78, 239])

A small time benchmark: element-wise operation with np is about 15 times faster on the tested machine.

In [8]:
a = np.arange(10000)
%timeit a + 1

7.16 µs ± 292 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
an = range(1000)
%timeit [i+1 for i in an]

71 µs ± 340 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Note array multiplication is not matrix multiplication

In [10]:
c = np.ones((3,3))
c*c ## array multip

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
c.dot(c) ## .dot does matrix multiplication

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [12]:
[2**0, 2**1, 2**2, 2**3, 2**4]

[1, 2, 4, 8, 16]

In [13]:
j = np.arange(10)
a = 2**(3*j)-j
print(a)

[        1         7        62       509      4092     32763    262138
   2097145  16777208 134217719]


## Other options

In [14]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,3])
a == b

array([False,  True, False, False], dtype=bool)

In [15]:
a >= b

array([False,  True,  True,  True], dtype=bool)

In [16]:
## Array-wise comparisons with np.array
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

np.array_equal(a,b)


False

In [17]:
np.array_equal(c, a)

True

In [18]:
# Logical and and or
a = np.array([0,0,1,1], dtype=bool)
b = np.array([0,1,0,1], dtype=bool)
np.logical_and(a,b)

array([False, False, False,  True], dtype=bool)

In [19]:
np.logical_or(a,b)

array([False,  True,  True,  True], dtype=bool)

In [20]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [21]:
np.log(a)

/Users/FamilieZhang/Software/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436])

In [22]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [23]:
a = np.triu(np.ones((3,3)),1)
a

array([[ 0.,  1.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.]])

In [24]:
a.T

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  1.,  0.]])

Note that __transpose__ is a view, but a copy.

In [25]:
a = np.array((0,1,2,3+1e-6))
b = np.array((0,1,2-1e-6,3))
np.array_equal(a,b)

False

In [26]:
np.allclose(a,b)

True

## Basic reductions

In [27]:
x = np.array([3,4,5,6])
np.sum(x)

18

In [28]:
x.sum()

18

### Sum by rows and by columns

In [29]:
x = np.array([[1,3],[4,5]])
x

array([[1, 3],
       [4, 5]])

In [30]:
x.sum(axis=0) ## columns - first dimension!! Different from R

array([5, 8])

In [31]:
x[:,0].sum(), x[:,1].sum()

(5, 8)

In [32]:
x.sum(axis=1) ## rows - the second dimension!! Different from R

array([4, 9])

In [33]:
x[0,:].sum(), x[1,:].sum()

(4, 9)

In [34]:
## Example of high-dimensional arrays
xh = np.random.rand(2,2,2)
xh

array([[[ 0.34866086,  0.36909763],
        [ 0.16106448,  0.08573028]],

       [[ 0.22221369,  0.64443585],
        [ 0.1476711 ,  0.82618531]]])

In [35]:
xh.sum(axis=2)

array([[ 0.71775849,  0.24679476],
       [ 0.86664954,  0.97385641]])

In [36]:
xh.sum(axis=1)

array([[ 0.50972535,  0.45482791],
       [ 0.36988479,  1.47062115]])

In [37]:
xh.sum(axis=0)

array([[ 0.57087456,  1.01353348],
       [ 0.30873559,  0.91191559]])

In [38]:
xh[0,1,:].sum()

0.24679476405529754

### Max and min, and argmax and argmin

In [39]:
x = np.array([1,3,5,2])
x.min()

1

In [40]:
x.max()

5

In [41]:
x.argmin() ## which.min in R

0

In [42]:
x.argmax()

2

### Logical operations

In [43]:
np.all([True, True, False])

False

In [44]:
np.any([True, True, False])

True

In [45]:
a = np.zeros((100,100))
np.any(a != 0)

False

In [46]:
## np.all() is equal to boolarray.all()
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = b + 1
((a <= b) & (b <= c)).all()

True

In [47]:
np.all(((a <= b) & (b <= c)))

True

### Statistics

In [48]:
x = np.array([1,2,3,1])
x.mean()

1.75

In [49]:
## note that the median is not a method of array, but rather a function
np.median(x)

1.5

In [50]:
## though there is also a function with the same name
np.mean(x)

1.75

In [51]:
x.std() ## full population standard deviation!!

0.82915619758884995

In [52]:
np.std(x, ddof=1) ## this is the '''normal''' sample s.d. like in R

0.9574271077563381

In [53]:
y = np.array([[1,2,3],[6,7,8]])
np.median(y, axis=1) ## the second dimension, row

array([ 2.,  7.])

In [54]:
np.median(y, axis=0) ## the first dimension, col

array([ 3.5,  4.5,  5.5])

In [55]:
np.median(y, axis=-1) ## the last dimension, row

array([ 2.,  7.])

### Worked example of statistics

In [56]:
!cat data/populations.txt

# year	hare	lynx	carrot
1900	30e3	4e3	48300
1901	47.2e3	6.1e3	48200
1902	70.2e3	9.8e3	41500
1903	77.4e3	35.2e3	38200
1904	36.3e3	59.4e3	40600
1905	20.6e3	41.7e3	39800
1906	18.1e3	19e3	38600
1907	21.4e3	13e3	42300
1908	22e3	8.3e3	44500
1909	25.4e3	9.1e3	42100
1910	27.1e3	7.4e3	46000
1911	40.3e3	8e3	46800
1912	57e3	12.3e3	43800
1913	76.6e3	19.5e3	40900
1914	52.3e3	45.7e3	39400
1915	19.5e3	51.1e3	39000
1916	11.2e3	29.7e3	36700
1917	7.6e3	15.8e3	41800
1918	14.6e3	9.7e3	43300
1919	16.2e3	10.1e3	41300
1920	24.7e3	8.6e3	47300


In [57]:
pop = np.loadtxt('data/populations.txt')
year, hares, lynxes, carrots = pop.T ## trick: column to variables

In [ ]:
from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
plt.axes([0.2, 0.1, 0.5, 0.8]) ## note it is axes, not axis
plt.plot(year, hares, year, lynxes, year, carrots)
plt.legend(('Hare', 'Lynx', 'Carrot'), loc=[1.05, 0.5])

In [ ]:
pop

In [ ]:
populations = pop[:, 1:]
populations

In [ ]:
populations.mean(axis=0) ## average

In [ ]:
populations.std(axis=0, ddof=1) ## sample standard deviations

In [ ]:
np.argmax(populations, axis=1) ## which species has the highest population each year

## Diffusion using a random walk algorithm

In [ ]:
n_stories = 1000 ## number of walkers
t_max = 200  ## time during which we follow the walker

t = np.arange(t_max)
steps = 2 * np.random.randint(0, 2, (n_stories, t_max)) -1
np.unique(steps)

In [ ]:
positions = np.cumsum(steps, axis=1) ## axis=1, dimension of time
sq_distance = positions ** 2

In [ ]:
msq = np.mean(sq_distance, axis=0)

In [ ]:
plt.figure(figsize=(4,3))
plt.plot(t, np.sqrt(msq), 'g.', t, np.sqrt(t), 'y-')
plt.xlabel(r"$t$")
plt.ylabel(r"$\sqrt{\langle (\delta x)^2 \rangle}$")

# Broadcasting

It’s possible to do operations on arrays of different sizes if NumPy can transform these arrays so that they all have
the same size: this conversion is called broadcasting.

In [ ]:
a = np.tile(np.arange(0,40,10), (3,1)).T
a

In [ ]:
b = np.array([0,1,2])
b

In [ ]:
a + b

In [ ]:
a = np.ones((4,5))
a

In [ ]:
a[0] = 2 ## implicit broadcasting: we assign an array of dimension 0 to an array of dimension 1
a

Use np.newaxis to add dimenstion

In [ ]:
a = np.arange(0,40,10)
a.shape

In [ ]:
a = a[:, np.newaxis]
a.shape
a

In [ ]:
a + b

## Worked Example: Route 66

In [ ]:
mileposts = np.array([0,198, 303, 736, 871, 1175, 1475, 544, 1913, 2448])

In [ ]:
## an intereseting way to generate pair-wise distance matrix given a vector
distance_array = abs(mileposts-mileposts[:, np.newaxis])
distance_array

In the example below, we calculate the distance from the origin of points on a 10x10 grid.

In [ ]:
x, y = np.arange(5), np.arange(5)[:, np.newaxis]
x,y

In [ ]:
distance = np.sqrt(x ** 2 + y ** 2)
distance

In [ ]:
plt.pcolor(distance)
plt.colorbar()

In [ ]:
## use numpy.ogrid to create the same example
x, y = np.ogrid[0:5, 0:5] ## notice the use of bracket!
x,y

In [ ]:
x.shape, y.shape

In [ ]:
distance = np.sqrt(x ** 2 + y ** 2)
distance

___np.ogrid___ is useful to handle computationals on a grid. On the other hand, ___np.mgrid___ directly provides matrices full of indices, namely without the need of broadcasting.

In [ ]:
x, y = np.mgrid[0:4, 0:4] ## use bracket!

In [ ]:
x

In [ ]:
y

# Array shape manipulation

## Flattening

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel() ## as.vector or unlist

In [ ]:
a.T ## transpose, note it's .T but not .T()

In [ ]:
a.T.ravel() ## row first

## Reshaping

In [ ]:
a.shape

In [ ]:
b = a.ravel()
b = b.reshape((2,3))
b

In [ ]:
a.reshape((3,-1)) ## in case last dimension is not specified, i.e. -1, it's atuoamtically guessed

np.reshape will return a view when possible, otherwise a copy

In [ ]:
b[0,0] = -1
a

In [ ]:
## an example of returning a copy
a = np.zeros((3,2))
b = a.T.reshape(6)
b[0] = 9.25
a

## Adding a dimension

Indexing with the ___np.newaxis__ object allows to add an axis to an array.

In [ ]:
z = np.array([1,2,3])
z

In [ ]:
z[:, np.newaxis]


In [ ]:
z[np.newaxis,:]

## Dimension shuffling

In [ ]:
a = np.arange(4*3*2).reshape((4,3,2))
a.shape

In [ ]:
a

In [ ]:
a[0,2,1]

In [ ]:
b = a.transpose(1,2,0) ## transpose does dimension shuffling
b

In [ ]:
b.shape

In [ ]:
b[2,1,0]

## Resizing

In [ ]:
a = np.arange(4)
a.resize((8,))
a

However, the array to be resized must __not__ be referenced elsewhere

In [ ]:
b = a
a.resize((4,))

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a

In [ ]:
id(a)

In [ ]:
ar = a.ravel()
af = a.flatten()

In [ ]:
np.all(ar == af)

In [ ]:
id(ar)

In [ ]:
id(af)

In [ ]:
id(a)

___ndarray.flatten___ returns a __copy__ of the array collapsed into oe dimension.

# Sorting data

In [ ]:
a = np.array([[5,6,4],[2,-1,7]])